name: Update Icon

on: [workflow_dispatch]

jobs:
  update-icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Update svg Icons
        run: FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }} FIGMA_FILE_KEY=${{ secrets.FIGMA_FILE_KEY }} npm run figma
      - name: Generate React Components
        run: npm run build:svg
      - name: Format
        run: npx prettier ./src --write
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat:ðŸŽ¸ update icons from figma'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: feat/update-icons
          branch-suffix: timestamp
          delete-branch: true
          title: 'feat:ðŸŽ¸ update icons from figma'
          body: Icons has been updated
